---
# tasks file for tomcat

- name: Running apt update
  apt:
    update_cache: true

- name: Installing Java
  apt:
    name: "{{ java_package }}"
    state: latest

- name: Installing Tomcat Server
  get_url:
      url: "{{ tomcat_url }}"
      dest: "{{ destination_folder }}"

- name: Extracting tar file
  unarchive:
     src: "{{ item }}"
     dest: "{{ destination_folder }}"
     remote_src: yes
  with_items:
    - "{{ destination_folder_path }}"

- name: Changing the port number using template
  template:
    src: template/server.xml.j2
    dest: "{{ tomcat_server_path }}"

- name: commenting in manager folder
  template:
    src: template/context.xml.j2
    dest: "{{ tomcat_manager_path }}"

- name: commenting in host-manager folder
  template:
    src: template/contexthm.xml.j2
    dest: "{{ tomcat_hostmanager_path }}"

- name: adding users
  template:
    src: template/tomcat-users.xml.j2
    dest: "{{ tomcat_user_path }}"

